CREATE TABLE `teste` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`teste` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
